config/routes.rb
Rails.application.routes.draw do
  get 'serials/:serial_id/:episode_id', to: 'episodes#show', as: :serial_episode

  resources :serials, only: :index  do
    resources :reviews, only: :create
  end

  resources :films, only: [:index, :show] do
    resources :reviews, only: :create
  end

  root 'movies#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :episode_number, presence: true, :numericality => { greater_than_or_equal_to: 1 }
  has_attached_file :video
  validates_attachment_content_type :video, :content_type => ['video/mp4']

  belongs_to :serial
end

app/models/film.rb
class Film < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, uniqueness: true
  has_attached_file :picture
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  has_attached_file :video
  validates_attachment_content_type :video, :content_type => ['video/mp4']

  has_many :reviews, as: :reviewable
end

app/models/review.rb
class Review < ApplicationRecord
  validates :text, presence: true

  belongs_to :reviewable, polymorphic: true
end

app/models/serial.rb
class Serial < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, uniqueness: true
  has_attached_file :picture
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  has_many :episodes
  has_many :reviews, as: :reviewable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :find_serial
  before_action :set_review
  before_action :set_rating

  def show
    @episodes = @serial.episodes
    @episode = @serial.episodes.friendly.find(params[:episode_id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def find_serial
    @serial = Serial.friendly.find(params[:serial_id])
  end

  def set_review
    @review = @serial.reviews.new
  end

  def set_rating
    @reviews = @serial.reviews

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :find_film, only: :show
  before_action :set_review, only: :show
  before_action :set_rating, only: :show

  def index
    @films = Film.all
  end

  def show

  end

  private

  def find_film
    @film = Film.friendly.find(params[:id])
  end

  def set_review
    @review = @film.reviews.new
  end

  def set_rating
    @reviews = @film.reviews

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    # sort_by.reverse - fastest way to sort date by desc
    # proof: http://stackoverflow.com/questions/2642182/sorting-an-array-in-descending-order-in-ruby
    @movies = (Serial.all + Film.all).sort_by { |movie| movie.created_at }.reverse
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_movie

  def create
    @review = @movie.reviews.create(review_params)

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def find_movie
    resource, id = request.path.split('/')[1,2]
    @movie = resource.singularize.classify.constantize.friendly.find(id)
  end

  def review_params
    params.require(:review).permit(:rating, :text)
  end

end

app/controllers/serials_controller.rb
class SerialsController < ApplicationController
  def index
    @serials = Serial.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/serials_helper.rb
module SerialsHelper
end

app/views/episodes/_episode.html.haml
#episode
  = video_tag @episode.video, :size => "900x550", :controls => true

  %br
  %br
  #change_episode
    - @episodes.each do |episode|
      - if episode == @episode
        = link_to "#{episode.episode_number}", serial_episode_path(@serial, episode), class: "btn disabled"
      - else
        = link_to "#{episode.episode_number}", serial_episode_path(@serial, episode), remote: true, class: "btn"

app/views/episodes/show.html.haml
.container
  %a.breadcrumb= link_to 'Home', root_path, class: 'teal-text'
  %a.breadcrumb= link_to 'Serials', serials_path, class: 'teal-text'
  %a.breadcrumb= link_to "#{@serial.name}", serial_episode_path(@serial, @serial.episodes.first), class: 'teal-text'

  .right
    .star-rating{'data-score' => "#{@avg_review}"}

  .center
    = render 'episode'

  %br
  %br
  %br
  .center
    = link_to 'Leave a review', "javascript:;", id: "reviews-link", :remote => true, class: 'btn teal-text waves-effect chip white waves-grey'
  #leave_review
    #review_form
      = render "reviews/form", movie: @serial, review: @review
    %ul
      #reviews_section
        - @serial.reviews.reverse[1..-1].each do |review|
          %li
            .star-rating{'data-score' => "#{review.rating}"}
          %li= review.text
          %li.divider

:javascript
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });

app/views/episodes/show.js.erb
$("#episode").html("<%= escape_javascript(render @episode) %>");

app/views/films/index.html.haml
.masonry-grid
  - @films.each do |film|
    #card.card.teal.lighten-2
      .card-image.waves-effect.waves-block.waves-light
        = link_to (image_tag film.picture), film
      .card-content
        %span.card-title.center
          = link_to "#{film.name}", film, class: "white-text"

app/views/films/show.html.haml
.container
  %a.breadcrumb= link_to 'Home', root_path, class: 'teal-text'
  %a.breadcrumb= link_to 'Films', films_path, class: 'teal-text'
  %a.breadcrumb= link_to "#{@film.name}", @film, class: 'teal-text'

  .right
    .star-rating{'data-score' => "#{@avg_review}"}

  .center
    = video_tag @film.video, :size => "900x550", :controls => true

  %br
  %br
  %br
  .center
    = link_to 'Leave a review', "javascript:;", id: "reviews-link", :remote => true, class: 'btn teal-text waves-effect chip white waves-grey'
  #leave_review
    #review_form
      = render "reviews/form", movie: @film, review: @review
    %ul
      #reviews_section
        - @film.reviews.reverse[1..-1].each do |review|
          %li
            .star-rating{'data-score' => "#{review.rating}"}
          %li= review.text
          %li.divider

:javascript
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Serials
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %body
      .ilike-dark-container
        %nav
          .container
            .nav-wrapper
              %a.brand-logo= link_to 'FMOVIES', root_path
              %ul#nav-mobile.right.hide-on-med-and-down
                %li= link_to 'Films', films_path
                %li= link_to 'Serials', serials_path

        %br
        .center.red-text
          - flash.each do |name, msg|
            = content_tag(:div, msg, class: "alert")

        = yield

        %footer.page-footer
          .container.center
            %h5.white-text FMOVIES
            %p.white-text  Only best content

          .footer-copyright
            .container.white-text
              ©  Made by
              %a.white-text.text-lighten-1{:href => "http://github.com/floodico"} floodico

app/views/movies/index.html.haml
.masonry-grid.transitions-enabled
  - @movies.each do |movie|
    #card.card.teal.lighten-2
      - if movie.is_a?(Serial)
        .card-image.waves-effect.waves-block.waves-light
          = link_to (image_tag movie.picture), serial_episode_path(movie, movie.episodes.first)
          %a.btn-large.btn-floating.halfway-fab.teal.lighten-2
            .center
              %h6= movie.episodes.count
        .card-content
          %span.card-title.center
            = link_to "#{movie.name}", serial_episode_path(movie, movie.episodes.first), class: "white-text"
      - else
        .card-image.waves-effect.waves-block.waves-light
          = link_to (image_tag movie.picture), movie
        .card-content
          %span.card-title.center
            = link_to "#{movie.name}", movie, class: "white-text"

app/views/reviews/_form.html.haml
= simple_form_for [movie, review], remote: true do |f|
  #rating-form
    %label Rating
  %br  
  = f.input :text, label: 'Comment'
  = f.button :submit

:javascript
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });

app/views/reviews/_review.html.haml
#review
  %ul
    %li
      .star-rating{"data-score" => "#{review.rating}"}
    %li= review.text
    %li.divider

:javascript
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });

app/views/reviews/create.js.erb
$('#reviews_section').prepend("<%= j render @review %>");
$('#rating-form').val("");
$('#review_text').val("");
$('#review_text').focus();

app/views/serials/index.html.haml
.masonry-grid.transitions-enabled
  - @serials.each do |serial|
    #card.card.teal.lighten-2
      .card-image.waves-effect.waves-block.waves-light
        = link_to (image_tag serial.picture), serial_episode_path(serial, serial.episodes.first)
        %a.btn-large.btn-floating.halfway-fab.waves-effect.waves-light.red.teal.lighten-2
          .center
            %h6= serial.episodes.count
      .card-content
        %span.card-title.center
          = link_to "#{serial.name}", serial_episode_path(serial, serial.episodes.first), class: "white-text"